#!/bin/sh
# Mute toggle.
set -x
if [ -x /usr/bin/pactl ]; then
  pactl set-sink-mute `pactl info | grep "Default Sink" | cut -d " " -f3` toggle
else
  OPTS=
  case `hostname` in
    kaveri)
      OPTS="-c 1"
      ;;
  esac
  
  if amixer $OPTS get Master | grep -q off; then
    amixer $OPTS set Master unmute
  else
    amixer $OPTS set Master mute
  fi
fi

# vim:sw=2:ts=2:sts=2:et:cc=80
# End of file
