#!/bin/sh
# Status line for dwm status bar.
set -e

separator() { echo -n "$1$2"; }

cpu_stat() {
  echo -n "`uptime | awk '{printf "%.2f\n", $(NF-2)}'`"
}

mem_stat() {
  echo -n "`free -m | awk 'NR==2{ printf "%s/%s/%.2f%%\n", $3,$2,$3*100/$2 }'`"
}

volume() {
  case `hostname` in
    kaveri)
      echo -n "`amixer -c1 get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/'`"
      ;;
    d311)
      echo -n "`amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/'`"
      ;;
  esac
}

disk_avail() {
  pattern=$1
  name=$2
  echo -n "${name}`df -h | grep "$pattern" | awk '{print $4}'`"
}

service() {
  service=$1
  name=$2
  if pgrep -x $service > /dev/null 2>&1; then
    echo -n "$name"
    return 0
  fi
  return 1
}

wifi_signal() {
  iface=$1
  echo -n `iw dev $iface station dump -v | awk '/signal:/{print $2}'`
}

datetime() {
  #echo "$(date +'%a %d %b %H:%M')"
  echo "`date +'%a%d %H:%M'`"
}

battery() {
  if [ -d /sys/class/power_supply/BAT0 ]; then
    capacity=`cat /sys/class/power_supply/BAT0/capacity`
    status=`cat /sys/class/power_supply/BAT0/status`

    if [ "$status" = "Charging" ]; then
      echo -n "chr: $capacity%"
    else
      echo -n "bat: $capacity%"
    fi
  fi
}

### main
battery
separator ' | vol: '
volume

separator ' | avg_mem: '
cpu_stat
separator '/'
mem_stat

separator ' | dsk_free: '
case `hostname` in
  kaveri)
    disk_avail kaveri-root root
    separator ' '
    disk_avail crypt db
    separator ' '
    disk_avail pkgmk pkgmk
    ;;
  d311)
    disk_avail /boot boot
    separator ' '
    disk_avail '\-root' root
    separator ' '
    disk_avail pkgmk pkgmk
    ;;
esac

separator ' | net: '

service nfsd            nfs       && separator ' '
service chronyd         ntp       && separator ' '
service sshd            sshd      && separator ' '
service tor             tor       && separator ' '
service polipo          polipo    && separator ' '
service dhcpcd          dhcp      && separator ' '
service sdhcp           dhcp      && separator ' '

service wpa_supplicant  wpa       && separator '[' \
  && wifi_signal wlp1s0 && separator '] '

separator '| '

datetime

# vim:ft=sh:sw=2:ts=2:sts=2:et:cc=80
# End of file
