#!/bin/sh
#
# Make screenshots via ImageMagick
#

OUTPUT=${OUTPUT:-$HOME/screenrec}
FORMAT=$(date +%y-%m-%y-%H:%M:%S).png

[ -d $OUTPUT ] || mkdir -p $OUTPUT

import -quality 100 -window root $OUTPUT/$FORMAT

# End of file
